-- Пересоздание схемы public для чистого запуска
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TABLE users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	full_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	phone VARCHAR(50),
	role VARCHAR(50) NOT NULL DEFAULT 'customer',
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sellers (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	store_name VARCHAR(255) NOT NULL,
	description TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Иерархическая связь
CREATE TABLE categories (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	seller_id BIGINT NOT NULL REFERENCES sellers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	price DECIMAL(10, 2) NOT NULL CHECK (price > 0),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE addresses (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	city VARCHAR(255) NOT NULL,
	street VARCHAR(255) NOT NULL,
	house VARCHAR(50) NOT NULL,
	apartment VARCHAR(50)
);

CREATE TABLE orders (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	status VARCHAR(50) NOT NULL DEFAULT 'Pending',
	total_amount DECIMAL(10, 2) NOT NULL CHECK (total_amount > 0),
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- (M:N)
CREATE TABLE order_items (
	order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE, 
	product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	quantity INT NOT NULL CHECK (quantity > 0),
	unit_price DECIMAL(10, 2) NOT NULL CHECK (unit_price > 0),
	PRIMARY KEY (order_id, product_id)
);

CREATE TABLE deliveries (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
	address_id BIGINT NOT NULL REFERENCES addresses(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	delivery_status VARCHAR(50) NOT NULL DEFAULT 'Pending',
	delivery_date TIMESTAMPTZ
);

CREATE TABLE payments (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	amount DECIMAL(10, 2) NOT NULL CHECK (amount > 0),
	status VARCHAR(50) NOT NULL DEFAULT 'Pending',
	paid_at TIMESTAMPTZ
);

CREATE TABLE carts (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- (M:N)
CREATE TABLE cart_items (
	cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE ON UPDATE CASCADE,
	product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	quantity INT NOT NULL CHECK (quantity > 0),
	PRIMARY KEY (cart_id, product_id)
);

-- (1:1)
CREATE TABLE stock (
	product_id BIGINT PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	quantity INT NOT NULL CHECK (quantity >= 0) DEFAULT 0,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- (M:N)
CREATE TABLE reviews (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
	score INT NOT NULL CHECK (score BETWEEN 1 AND 5),
	comment TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);